Fix staticcheck Warnings
Clean up all the staticcheck warnings:

parse/number.go:33:48: error strings should not be capitalized (ST1005)
parse/number.go:62:48: error strings should not be capitalized (ST1005)
parse/number.go:91:48: error strings should not be capitalized (ST1005)
parse/number.go:105:48: error strings should not be capitalized (ST1005)
parse/number.go:118:48: error strings should not be capitalized (ST1005)
parse/number.go:131:48: error strings should not be capitalized (ST1005)
parse/parse_string.go:10:2: var stringSliceType is unused (U1000)
parse/parse_string.go:11:2: var boolSliceType is unused (U1000)
parse/parse_string.go:12:2: var intSliceType is unused (U1000)
parse/parse_string.go:13:2: var int8SliceType is unused (U1000)
parse/parse_string.go:14:2: var int16SliceType is unused (U1000)
parse/parse_string.go:15:2: var int32SliceType is unused (U1000)
parse/parse_string.go:16:2: var int64SliceType is unused (U1000)
parse/parse_string.go:17:2: var uintSliceType is unused (U1000)
parse/parse_string.go:18:2: var uint8SliceType is unused (U1000)
parse/parse_string.go:19:2: var uint16SliceType is unused (U1000)
parse/parse_string.go:20:2: var uint32SliceType is unused (U1000)
parse/parse_string.go:21:2: var float32SliceType is unused (U1000)
parse/parse_string.go:22:2: var float64SliceType is unused (U1000)
parse/parse_string.go:23:2: var complex64SliceType is unused (U1000)
parse/parse_string.go:24:2: var complex128SliceType is unused (U1000)
parse/parse_string.go:82:29: error strings should not be capitalized (ST1005)
parse/parse_string.go:92:27: error strings should not be capitalized (ST1005)
parse/parse_string.go:106:11: error strings should not be capitalized (ST1005)
ptrify/ptrify_test.go:13:7: type sBool is unused (U1000)
ptrify/ptrify_test.go:15:7: type sBoolPtr is unused (U1000)
sources/env/env.go:56:10: error strings should not be capitalized (ST1005)
sources/flag/flag.go:151:9: error strings should not be capitalized (ST1005)
sources/flag/flag.go:388:10: error strings should not be capitalized (ST1005)
sources/flag/flag.go:425:3: redundant return statement (S1023)
sources/flag/flag.go:478:8: error strings should not be capitalized (ST1005)
sources/flag/flag_test.go:159:2: ineffective assignment to field tu.Text (SA4005)
sources/pflag/pflag.go:141:9: error strings should not be capitalized (ST1005)
sources/pflag/pflag.go:408:10: error strings should not be capitalized (ST1005)
sources/pflag/pflag.go:441:3: redundant return statement (S1023)
sources/pflag/pflag.go:474:8: error strings should not be capitalized (ST1005)
sources/pflag/pflag_test.go:162:2: ineffective assignment to field tu.Text (SA4005)
tagformat/caseconversion/case_conversion.go:30:15: error strings should not be capitalized (ST1005)
tagformat/caseconversion/case_conversion.go:36:16: error strings should not be capitalized (ST1005)
tagformat/caseconversion/case_conversion.go:57:15: error strings should not be capitalized (ST1005)
tagformat/caseconversion/case_conversion.go:67:15: error strings should not be capitalized (ST1005)
tagformat/caseconversion/case_conversion.go:158:15: error strings should not be capitalized (ST1005)
tagformat/caseconversion/case_conversion.go:205:15: error strings should not be capitalized (ST1005)
tagformat/caseconversion/case_conversion.go:218:16: error strings should not be capitalized (ST1005)
tagformat/caseconversion/case_conversion.go:244:15: error strings should not be capitalized (ST1005)
tagformat/caseconversion/case_conversion.go:257:16: error strings should not be capitalized (ST1005)
tagformat/caseconversion/case_conversion.go:273:15: error strings should not be capitalized (ST1005)
tagformat/caseconversion/case_conversion.go:287:16: error strings should not be capitalized (ST1005)
tagformat/caseconversion/case_conversion.go:307:17: strings.Title has been deprecated since Go 1.18 and an alternative has been available since Go 1.0: The rule Title uses for word boundaries does not handle Unicode punctuation properly. Use golang.org/x/text/cases instead.  (SA1019)
tagformat/caseconversion/case_conversion.go:321:17: strings.Title has been deprecated since Go 1.18 and an alternative has been available since Go 1.0: The rule Title uses for word boundaries does not handle Unicode punctuation properly. Use golang.org/x/text/cases instead.  (SA1019)
transform/flatten_mangler.go:262:24: error strings should not be capitalized (ST1005)